#!/bin/bash
#PBS -l select=1:ncpus=24:mpiprocs=24:nodetype=haswell_reg
#PBS -P CSCI1142
#PBS -q smp
#PBS -l walltime=90:00:00
#PBS -o /mnt/lustre/users/jsmith1/job.out
#PBS -e /mnt/lustre/users/jsmith1/job.err
#PBS -m abe
#PBS -M smtjul022@myuct.ac.za
#PBS -N ECSUPG_0_10000

ulimit -s unlimited

cd /mnt/lustre/users/jsmith1/Hexapod---SUPG/JSUPG/

python3 /mnt/lustre/users/jsmith1/Hexapod---SUPG/JSUPG/example_run.py 500 ECSUPGTest