#!/bin/bash

#PBS -l select=1:ncpus=24:mpiprocs=24:nodetype=haswell_reg
#PBS -P CSCI1142
#PBS -q smp
#PBS -l walltime=04:00:00
#PBS -o /mnt/lustre/users/jsmith1/job.out
#PBS -e /mnt/lustre/users/jsmith1/job.err
#PBS -m abe
#PBS -M jsmith1@myuct.ac.za
#PBS -N neat_f_5000

#ulimit -s unlimited

cd /mnt/lustre/users/jsmith1/Hexapod---SUPG/JSUPG
#nproc=`cat $PBS_NODEFILE | wc -l`
python3 /mnt/lustre/users/jsmith1/Hexapod---SUPG/JSUPG/example_run.py 5000 TEST0